
@host = http://localhost:3000


// -- Autores --------------------------------------------------------------------------/

//Crear un autor
POST {{host}}/api/autores
Content-Type: application/json

{
    "nombre": "Lorca", 
    "email": "bbb@gmail.com",
    "imagen": "https://i.imgur.com/VEIKbp0.png"
}


###
//Recuperar 1 autor
GET {{host}}/api/autores/22

###
//Actualizar un autor
PUT {{host}}/api/autores/15
Content-Type: application/json

{
    "email": "fffff@gmail.com",
}

###
//Borrar un autor
DELETE {{host}}/api/autores/23


// -- Posts --------------------------------------------------------------------------/

###
//Crear un post
POST {{host}}/api/posts
Content-Type: application/json

{
    "titulo": "Mi ultimo blog", 
    "descripcion": "Primer blog descripción del mundo",
    "categoria":"1",
    "autores_id":23
}

###
//Recuperar un post
GET {{host}}/api/posts/10

###
//Recuperar posts por autor
GET {{host}}/api/posts/getByAutor/22

###
//Actualizar un post
PUT {{host}}/api/posts/9
Content-Type: application/json

{
    "fecha_creacion": "2025-09-08"
}

###
//Borrar un post
DELETE {{host}}/api/posts/9