
@host = http://localhost:3000

//Crear un autor
POST {{host}}/api/autores
Content-Type: application/json

{
    "nombre": "Lorca", 
    "email": "asddddd@gmail.com",
    "imagen": "https://i.imgur.com/VEIKbp0.png"
}


###
//Recuperar 1 autor
GET {{host}}/api/autores/20



###
//Crear un post
POST {{host}}/api/posts
Content-Type: application/json

{
    "titulo": "Octavo blog", 
    "descripcion": "Primer blog descripción del mundo",
    "fecha_creacion": "2023-09-01",
    "categoria":"1",
    "autores_id":20
}

###
//Recuperar un post
GET {{host}}/api/posts/9

###
//Recuperar posts por autor
GET {{host}}/api/posts/getByAutor/77

###
//Actualizar un post

PUT {{host}}/api/posts/9
Content-Type: application/json

{
    "fecha_creacion": "2025-09-08"
}
